version: 2.1
orbs:
  node: circleci/node@4
  browser-tools: circleci/browser-tools@1
  codecov: codecov/codecov@3
jobs:
  test:
    docker:
      - image: cimg/node:current-browsers
        environment:
            CHROME_BIN: '/usr/bin/google-chrome'
      - image: scttcper/plex-with-media
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/install-packages
      - run:
          name: claim-server
          command: npm run claim-server
      - run:
          name: add-media
          command: npm run add-media
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: './reports'
            JEST_JUNIT_OUTPUT_NAME: 'test-results.xml'
      - store_test_results:
          path: ./reports
      - codecov/upload
  cleanup:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npm run test-cleanup
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - cleanup
      - test:
          requires:
            - cleanup
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
